---
  - name: Install missing dependences in RedHat system
    yum: pkg={{ item }} state=installed
    with_items: 
     - "@Development Tools"
     - csh
     - tcsh
     - tcl-devel
     - openmpi
     - openmpi-devel
     - gcc-c++.x86_64
    environment:
     PATH: /usr/lib64/openmpi/bin/:{{ ansible_env.PATH }}

  - name: Download and untar MPICH(v3.2) source code
    unarchive:
      src: http://www.mpich.org/static/downloads/3.2/mpich-3.2.tar.gz
      dest: /tmp
      creates: /tmp/mpich-3.2
      remote_src: yes
      mode: 0755

  - name: Configure the building directory for MPICH
    command: ./configure
    args:
      chdir: /tmp/mpich-3.2/
    become: yes

  - name: Building MPICH
    make:
      chdir: /tmp/mpich-3.2/
      target: install
    become: yes

  - name: Compile charm-6.7.0 libraries with MPI support
    shell:
      env MPICXX=/usr/local/bin/mpicxx MPICC=/usr/local/bin/mpicc ./build charm++ mpi-linux-x86_64 --with-production
    args:
      chdir: "{{ install_path }}/NAMD_2.11_Source/charm-6.7.0/"
      creates: "{{ install_path }}/NAMD_2.11_Source/charm-6.7.0/bin"
